before_script: cd numbers
language: java
jdk: oraclejdk8
after_success:
  - echo "<settings><servers><server><id>ossrh</id><username>\${env.OSSRH_USERNAME}</username><password>\${env.OSSRH_PASSWORD}</password></server></servers></settings>" > ~/settings.xml
  - mvn deploy --settings ~/settings.xml
